from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .views import contact_us, evidence_crime_report_view, law_about, law_general, law_laws, report_child, report_property, report_election, report_state

urlpatterns = [
    path('',views.index,name='index'),
    path('userregister/', views.userregister, name='userregister'),
    path('witnessregister/', views.witnessregister, name='witnessregister'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('report_crime/', views.report_crime, name='report_crime'),
    path('reported_crimes/', views.reported_crimes, name='reported_crimes'),
    # path('generate_pdf/', views.generate_pdf, name='generate_pdf'),
    # path('generate_unique_fir_number/', views.generate_unique_fir_number, name='generate_unique_fir_number'),
    path('listcrime/', views.listcrime, name='listcrime'),
    path('about/', views.about, name='about'),
    path('general/', views.general, name='general'),
    path('laws/', views.laws, name='laws'),
    path('contact/', views.contact, name='contact'),
    path('gallery/', views.gallery, name='gallery'),
    path('anony_report/', views.anony_report, name='anony_report'),
    path('anony_pdf/', views.anony_pdf, name='anony_pdf'),
    path('law_index/', views.law_index, name='law_index'),
    path('law_login/', views.law_login, name='law_login'),
    path('law_update_status/', views.law_update_status, name='law_update_status'),
    path('update_status/', views.update_status, name='update_status'),
    path('verify/', views.verify, name='verify'),
    path('check_reporter_loc/', views.check_reporter_loc, name='check_reporter_loc'),
    path('crime_category/', views.crime_category, name='crime_category'),
    path('report_doc/', views.report_doc, name='report_doc'),
    path('report_public/', views.report_public, name='report_public'),
    path('upload_evidence/', views.upload_evidence, name='upload_evidence'),
    path('view_doc/<int:crime_id>/', views.view_doc, name='view_doc'),
    path('view_crime/<int:crime_id>/', views.view_crime, name='view_crime'),
    path('view_public/<int:crime_id>/', views.view_public, name='view_public'),
    path('prisonstaff', views.prisonstaff, name='prisonstaff'),
    path('control_page', views.control_page, name='control_page'),
    path('control_status', views.control_status, name='control_status'),
    path('control', views.control, name='control'),
    path('report_prison', views.report_prison, name='report_prison'),
    path('law_page', views.law_page, name='law_page'),
    path('up_final', views.up_final, name='up_final'),
    path('fir/', views.fir, name='fir'),
    path('witness/', views.witness, name='witness'),
    path('forensic/', views.forensic, name='forensic'),
    path('arrest/', views.arrest, name='arrest'),
    path('charge/', views.charge, name='charge'),
    path('case/', views.case, name='case'),
    path('final/', views.final, name='final'),
    path('book_appointment/', views.book_appointment, name='book_appointment'),
    path('appointment/', views.appointment_view, name='appointment_view'),
    path('evidence_crime_report/<int:crime_report_id>/',views.evidence_crime_report_view, name='evidence_crime_report'),
    path('evidence_doc_report/<int:crime_report_id>/',views.evidence_doc_report_view, name='evidence_doc_report'),
    path('evidence_public_report/<int:crime_report_id>/',views.evidence_public_report_view, name='evidence_public_report'),
    path('law_about/', law_about, name='law_about'),
    path('law_general/', law_general, name='law_general'),
    path('law_laws/', law_laws, name='law_laws'),
    path('report_property/', report_property, name='report_property'),
    path('report_child/', report_child, name='report_child'),
    path('report_election/', report_election, name='report_election'),
    path('report_state/', report_state, name='report_state'),
    
    path('firdoc/', views.firdoc, name='firdoc'),
    path('witnessdoc/', views.witnessdoc, name='witnessdoc'),
    path('forensicdoc/', views.forensicdoc, name='forensicdoc'),
    path('arrestdoc/', views.arrestdoc, name='arrestdoc'),
    path('chargedoc/', views.chargedoc, name='chargedoc'),
    path('casedoc/', views.casedoc, name='casedoc'),
    path('finaldoc/', views.finaldoc, name='finaldoc'),
    path('firpublic/', views.firpublic, name='firpublic'),
    path('witnesspublic/', views.witnesspublic, name='witnesspublic'),
    path('forensicpublic/', views.forensicpublic, name='forensicpublic'),
    path('arrestpublic/', views.arrestpublic, name='arrestpublic'),
    path('chargepublic/', views.chargepublic, name='chargepublic'),
    path('casepublic/', views.casepublic, name='casepublic'),
    path('finalpublic/', views.finalpublic, name='finalpublic'),
    path('contact_us/', contact_us, name='contact_us'),
    path('find_police_stations', views.find_police_stations, name='find_police_stations'),
    
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)