# Generated by Django 4.2.4 on 2023-10-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmatePlaces',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inmate',
            name='inmate_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeapp.inmateplaces'),
        ),
    ]
