# Generated by Django 4.2.4 on 2023-10-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0002_inmateplaces_alter_inmate_inmate_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='jailor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='ap_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
