# Generated by Django 4.2.4 on 2023-09-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='fir_number',
        ),
    ]
