# Generated by Django 4.2.4 on 2024-01-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0003_remove_appointment_booked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
