# Generated by Django 4.2.4 on 2024-01-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0004_customuser_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
