# Generated by Django 4.2.4 on 2023-09-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0004_remove_crimereport_fir_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('offender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offender_vehiclenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
