# Generated by Django 4.2.4 on 2023-09-13 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0005_anonyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='list_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
