# Generated by Django 4.2.4 on 2023-09-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0006_crimereport_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_victim',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_witness',
        ),
    ]
