# Generated by Django 4.2.4 on 2024-01-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0006_alter_crimereport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='reporter_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
    ]
