# Generated by Django 4.2.4 on 2024-01-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0007_alter_crimereport_reporter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencecrimereport',
            name='date_arrest',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencecrimereport',
            name='date_case',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencecrimereport',
            name='date_charge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencecrimereport',
            name='date_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencecrimereport',
            name='date_fir',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencecrimereport',
            name='date_forensic',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencecrimereport',
            name='date_witness',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
