# Generated by Django 4.2.4 on 2023-09-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0007_remove_customuser_is_victim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('FIR Verified', 'FIR Verified'), ('Investigation in progress', 'Investigation in progress'), ('Completed', 'Completed')], default='Reported', max_length=100),
        ),
    ]
