# Generated by Django 4.2.4 on 2024-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0008_evidencecrimereport_date_arrest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreport',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publicreport',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
