# Generated by Django 4.2.4 on 2024-01-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0009_docreport_report_date_publicreport_report_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidencePublicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_fir', models.FileField(blank=True, null=True, upload_to='evidence_fir/')),
                ('document_witness', models.FileField(blank=True, null=True, upload_to='evidence_witness/')),
                ('document_forensic', models.FileField(blank=True, null=True, upload_to='evidence_forensic/')),
                ('document_arrest', models.FileField(blank=True, null=True, upload_to='evidence_arrest/')),
                ('document_charge', models.FileField(blank=True, null=True, upload_to='evidence_charge/')),
                ('document_case', models.FileField(blank=True, null=True, upload_to='evidence_case/')),
                ('document_final', models.FileField(blank=True, null=True, upload_to='evidence_final/')),
                ('date_fir', models.DateTimeField(blank=True, null=True)),
                ('date_witness', models.DateTimeField(blank=True, null=True)),
                ('date_forensic', models.DateTimeField(blank=True, null=True)),
                ('date_arrest', models.DateTimeField(blank=True, null=True)),
                ('date_charge', models.DateTimeField(blank=True, null=True)),
                ('date_case', models.DateTimeField(blank=True, null=True)),
                ('date_final', models.DateTimeField(blank=True, null=True)),
                ('crime_idnum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeapp.publicreport')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceDocReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_fir', models.FileField(blank=True, null=True, upload_to='evidence_fir/')),
                ('document_witness', models.FileField(blank=True, null=True, upload_to='evidence_witness/')),
                ('document_forensic', models.FileField(blank=True, null=True, upload_to='evidence_forensic/')),
                ('document_arrest', models.FileField(blank=True, null=True, upload_to='evidence_arrest/')),
                ('document_charge', models.FileField(blank=True, null=True, upload_to='evidence_charge/')),
                ('document_case', models.FileField(blank=True, null=True, upload_to='evidence_case/')),
                ('document_final', models.FileField(blank=True, null=True, upload_to='evidence_final/')),
                ('date_fir', models.DateTimeField(blank=True, null=True)),
                ('date_witness', models.DateTimeField(blank=True, null=True)),
                ('date_forensic', models.DateTimeField(blank=True, null=True)),
                ('date_arrest', models.DateTimeField(blank=True, null=True)),
                ('date_charge', models.DateTimeField(blank=True, null=True)),
                ('date_case', models.DateTimeField(blank=True, null=True)),
                ('date_final', models.DateTimeField(blank=True, null=True)),
                ('crime_idnum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeapp.docreport')),
            ],
        ),
    ]
