# Generated by Django 4.2.4 on 2024-02-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0011_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docreport',
            name='email',
        ),
        migrations.AddField(
            model_name='docreport',
            name='reporter_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
