# Generated by Django 4.2.4 on 2023-09-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0011_crimereport_spec_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_loc', models.CharField(max_length=100)),
                ('enforcement_loc', models.CharField(max_length=100)),
            ],
        ),
    ]
