# Generated by Django 4.2.4 on 2024-02-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0012_remove_docreport_email_docreport_reporter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='crimestatus',
            field=models.CharField(default='Criminal Law', max_length=100),
        ),
    ]
