# Generated by Django 4.2.4 on 2023-09-18 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0012_specloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='spec_station',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='spec_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crimeapp.specloc'),
        ),
    ]
