# Generated by Django 4.2.4 on 2024-02-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0013_crimereport_crimestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='crimestatus',
            field=models.CharField(blank=True, default='Criminal Law', max_length=100, null=True),
        ),
    ]
