# Generated by Django 4.2.4 on 2024-02-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0014_alter_crimereport_crimestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='crimestatus',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='location_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
