# Generated by Django 4.2.4 on 2024-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0016_publicreport_location_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=15, null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
