# Generated by Django 4.2.4 on 2023-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0016_customuser_is_verified_customuser_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='offender_name',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='offender_vehiclenumber',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='time',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='witness_name',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='delay',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='off_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='offenderDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='victimDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='witnessInformation',
            field=models.TextField(null=True),
        ),
    ]
