# Generated by Django 4.2.4 on 2023-09-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0017_remove_crimereport_date_remove_crimereport_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='delay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='off_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='offenderDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='victimDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='witnessInformation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
