# Generated by Django 4.2.4 on 2023-09-25 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0018_alter_crimereport_datetime_alter_crimereport_delay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=100)),
                ('ano', models.CharField(default='', max_length=12)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('victimDescription', models.TextField(blank=True, null=True)),
                ('witnessInformation', models.TextField(blank=True, null=True)),
                ('offenderDescription', models.TextField(blank=True, null=True)),
                ('delay', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('FIR Verified', 'FIR Verified'), ('Investigation in progress', 'Investigation in progress'), ('Completed', 'Completed')], default='Reported', max_length=100)),
                ('threat', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Any kind of Threat or Violence faced')),
                ('list_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
