# Generated by Django 4.2.4 on 2023-09-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0019_docreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreport',
            name='evidence_vid_aud',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
