# Generated by Django 4.2.4 on 2023-09-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0020_docreport_evidence_vid_aud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docreport',
            old_name='evidence_vid_aud',
            new_name='evidence_pic_vid_aud',
        ),
    ]
