# Generated by Django 4.2.4 on 2023-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0023_remove_docreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docreport',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='docreport',
            name='threat',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Any kind of Threat or Violence faced'),
        ),
    ]
