# Generated by Django 4.2.4 on 2023-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0024_alter_docreport_mail_alter_docreport_threat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docreport',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
