# Generated by Django 4.2.4 on 2023-09-26 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0025_alter_docreport_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=100)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_location', models.CharField(max_length=100)),
                ('offen_type', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('aadhno', models.CharField(default='', max_length=12)),
                ('description', models.TextField()),
                ('victimDescription', models.TextField(blank=True, null=True)),
                ('witnessInformation', models.TextField(blank=True, null=True)),
                ('offenderDescription', models.TextField(blank=True, null=True)),
                ('delay', models.TextField(blank=True, null=True)),
                ('list_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spec_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crimeapp.specloc')),
            ],
        ),
    ]
