# Generated by Django 4.2.4 on 2023-10-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0028_docreport_status_publicreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docreport',
            name='evidence_pic_vid_aud',
        ),
        migrations.AddField(
            model_name='docreport',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_images/'),
        ),
    ]
