# Generated by Django 4.2.4 on 2023-10-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0029_remove_docreport_evidence_pic_vid_aud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('FIR Verified', 'FIR Verified'), ('Investigation in progress', 'Investigation in progress'), ('Completed', 'Completed')], default='Reported', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('FIR Verified', 'FIR Verified'), ('Investigation in progress', 'Investigation in progress'), ('Completed', 'Completed')], default='Reported', max_length=100, null=True),
        ),
    ]
