# Generated by Django 4.2.4 on 2023-10-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0030_alter_crimereport_status_alter_docreport_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docreport',
            old_name='mail',
            new_name='email',
        ),
    ]
