# Generated by Django 4.2.4 on 2023-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0032_alter_docreport_evidence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_prison',
            field=models.BooleanField(default=False),
        ),
    ]
