# Generated by Django 4.2.4 on 2023-10-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0033_customuser_is_control_customuser_is_prison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('Preliminary Investigation', 'Preliminary Investigation'), ('Inquiry and Investigation', 'Inquiry and Investigation'), ('Arrest and Detention', 'Arrest and Detention'), ('Case Closed', 'Case Closed')], default='Reported', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('Preliminary Investigation', 'Preliminary Investigation'), ('Inquiry and Investigation', 'Inquiry and Investigation'), ('Arrest and Detention', 'Arrest and Detention'), ('Case Closed', 'Case Closed')], default='Reported', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicreport',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Preliminary Investigation', 'Preliminary Investigation'), ('Inquiry and Investigation', 'Inquiry and Investigation'), ('Arrest and Detention', 'Arrest and Detention'), ('Case Closed', 'Case Closed')], default='Reported', max_length=100),
        ),
    ]
