# Generated by Django 4.2.4 on 2023-10-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0034_alter_crimereport_status_alter_docreport_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceCrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_fir', models.FileField(upload_to='evidence_fir/')),
                ('document_witness', models.FileField(upload_to='evidence_witness/')),
                ('document_forensic', models.FileField(upload_to='evidence_forensic/')),
                ('document_arrest', models.FileField(upload_to='evidence_arrest/')),
                ('document_charge', models.FileField(upload_to='evidence_charge/')),
                ('document_case', models.FileField(upload_to='evidence_case/')),
                ('document_final', models.FileField(upload_to='evidence_final/')),
                ('crime_idnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeapp.crimereport')),
            ],
        ),
    ]
