# Generated by Django 4.2.4 on 2023-10-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0035_evidencecrimereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencecrimereport',
            name='document_arrest',
            field=models.FileField(blank=True, null=True, upload_to='evidence_arrest/'),
        ),
    ]
