# Generated by Django 4.2.4 on 2023-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0036_alter_evidencecrimereport_document_arrest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencecrimereport',
            name='document_case',
            field=models.FileField(blank=True, null=True, upload_to='evidence_case/'),
        ),
        migrations.AlterField(
            model_name='evidencecrimereport',
            name='document_charge',
            field=models.FileField(blank=True, null=True, upload_to='evidence_charge/'),
        ),
        migrations.AlterField(
            model_name='evidencecrimereport',
            name='document_final',
            field=models.FileField(blank=True, null=True, upload_to='evidence_final/'),
        ),
        migrations.AlterField(
            model_name='evidencecrimereport',
            name='document_fir',
            field=models.FileField(blank=True, null=True, upload_to='evidence_fir/'),
        ),
        migrations.AlterField(
            model_name='evidencecrimereport',
            name='document_forensic',
            field=models.FileField(blank=True, null=True, upload_to='evidence_forensic/'),
        ),
        migrations.AlterField(
            model_name='evidencecrimereport',
            name='document_witness',
            field=models.FileField(blank=True, null=True, upload_to='evidence_witness/'),
        ),
    ]
