# Generated by Django 4.2.4 on 2023-10-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0037_alter_evidencecrimereport_document_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencecrimereport',
            name='crime_idnum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeapp.crimereport'),
        ),
    ]
