# Generated by Django 4.2.4 on 2024-02-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='place',
        ),
        migrations.AddField(
            model_name='advocate',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='office_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
