# Generated by Django 4.2.4 on 2024-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_app', '0002_remove_advocate_place_advocate_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDacoitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('date_time_incidence', models.DateTimeField()),
                ('num_perpetrators', models.IntegerField()),
                ('presence_weapon', models.CharField(blank=True, max_length=100, null=True)),
                ('description_incidence', models.TextField()),
                ('stolen_item', models.CharField(blank=True, max_length=255, null=True)),
                ('injury', models.CharField(blank=True, max_length=100, null=True)),
                ('witnesses', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
