# Generated by Django 4.2.4 on 2024-02-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_app', '0003_propertydacoitreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='advocate_photos/'),
        ),
    ]
